training:
  total_timesteps: 10000
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  policy: "MlpPolicy"
  policy_kwargs:
    net_arch: [64, 64]
  
environment:
  competitor_price_multiplier: 1.1
  demand_fluctuation_range: [0.8, 1.2]
  competitor_reaction_range: [0.95, 1.05]
  
business_rules:
  min_margin_multiplier: 1.15
  min_discount_multiplier: 0.7
  max_premium_multiplier: 1.3
  inventory_threshold: 100
  stockout_penalty_weight: 0.5